"""Backward-compatible re-export hub.

New code should import from the specific modules directly:
  _transcript_common, _transcript_parse, _transcript_index,
  _transcript_discover, _transcript_import
"""

from _transcript_common import (  # noqa: F401
    CLIENTS,
    SKIP_BLOCK_TYPES,
    TEXT_BLOCK_TYPES,
    TOOL_RESULT_TYPES,
    TOOL_USE_TYPES,
    deduplicate_messages,
    deduplicate_tool_events,
    earliest_timestamp,
    ensure_dict,
    ensure_list,
    extract_gemini_parts,
    extract_gemini_text,
    extract_simple_text,
    extract_text_blocks,
    find_first_mapping_with_keys,
    get_nested,
    join_paragraphs,
    load_json,
    load_jsonl,
    normalize_timestamp,
    parse_iso_timestamp,
    sha256_file,
    slugify,
    summarize_value,
    timestamp_partition,
    truncate,
    yaml_escape,
)
from _transcript_discover import (  # noqa: F401
    default_client_roots,
    default_global_transcript_root,
    discover_source_files,
    infer_project_slug,
    project_slugs_match,
    safe_file_mtime,
    transcript_matches_repo,
)
from _transcript_import import (  # noqa: F401
    append_jsonl,
    copy_file,
    import_transcript,
    manifest_changed,
    manifest_signature,
    preserve_existing_import_timestamp,
    transcript_has_content,
    write_clean_markdown,
    write_json,
)
from _transcript_index import upsert_search_index  # noqa: F401
from _transcript_parse import (  # noqa: F401
    ParsedTranscript,
    TranscriptMessage,
    TranscriptToolEvent,
    infer_client,
    parse_claude_transcript,
    parse_codex_transcript,
    parse_gemini_transcript,
    parse_transcript,
)

__all__ = [
    # _transcript_common
    "CLIENTS",
    "TEXT_BLOCK_TYPES",
    "SKIP_BLOCK_TYPES",
    "TOOL_USE_TYPES",
    "TOOL_RESULT_TYPES",
    "deduplicate_messages",
    "deduplicate_tool_events",
    "slugify",
    "sha256_file",
    "normalize_timestamp",
    "earliest_timestamp",
    "parse_iso_timestamp",
    "timestamp_partition",
    "join_paragraphs",
    "summarize_value",
    "truncate",
    "yaml_escape",
    "ensure_dict",
    "ensure_list",
    "get_nested",
    "load_jsonl",
    "load_json",
    "extract_text_blocks",
    "extract_simple_text",
    "extract_gemini_text",
    "extract_gemini_parts",
    "find_first_mapping_with_keys",
    # _transcript_parse
    "TranscriptMessage",
    "TranscriptToolEvent",
    "ParsedTranscript",
    "infer_client",
    "parse_transcript",
    "parse_codex_transcript",
    "parse_claude_transcript",
    "parse_gemini_transcript",
    # _transcript_index
    "upsert_search_index",
    # _transcript_discover
    "default_global_transcript_root",
    "default_client_roots",
    "discover_source_files",
    "infer_project_slug",
    "transcript_matches_repo",
    "project_slugs_match",
    "safe_file_mtime",
    # _transcript_import
    "import_transcript",
    "transcript_has_content",
    "write_clean_markdown",
    "preserve_existing_import_timestamp",
    "manifest_signature",
    "manifest_changed",
    "write_json",
    "append_jsonl",
    "copy_file",
]
